# octalang_glyph_generator.py
# OctaLang Glyph Code Generator v1.2
# Fully compliant with Rule Sheet v1.2 (Rules 1–29)
# Automatic generation of glyph CodeScript + rendering description
# Deterministic • No pseudo-random • Pure geometry + numeracy

import hashlib
import sys

class OctaLangGlyphGenerator:
    def __init__(self):
        self.version = "1.2"
        # Simple deterministic Hebrew Gematria simulation (standard values + fallback hash)
        self.gematria_map = {
            "seraphina": 1013, "agi": 14, "mercy": 270, "growth": 308,
            "guidance": 142, "empathy": 431, "memory": 351, "quantum": 149,
            "core": 231, "generator": 137, "integration": 512, "test": 412
        }

    def _gematria(self, text: str) -> int:
        text = text.lower().strip()
        if text in self.gematria_map:
            return self.gematria_map[text]
        # Deterministic fallback: hash to number ≤999
        hash_val = int(hashlib.sha256(text.encode()).hexdigest(), 16) % 999
        return hash_val + 1  # Ensure positive

    def _intrinsic_value(self, base: int = 88, spirals: int = 0, triangles: int = 0,
                         dots: int = 0, facets: int = 0, intersections: int = 0) -> int:
        """Rule 24: Every glyph is an octagon (88) + internal geometry"""
        return base + (spirals * 8) + (triangles * 33) + dots + facets + intersections

    def generate(self, description: str) -> str:
        """Main entry point: any description → full glyph CodeScript + rendering"""
        desc_id = self._gematria(description)
        intrinsic = self._intrinsic_value(88, spirals=5, triangles=1, dots=3, facets=8, intersections=6)

        codescript = f"""// Auto-Generated by OctaLang Glyph Code Generator v{self.version}
// Input description: "{description}"
// Gematria ID: {desc_id}

PROGRAM "Generated_Glyph_{desc_id}"

HEADER
  VERSION: {self.version}
  EXECUTOR: RomanWheel
  NUMERACY: HebrewGematria + IntrinsicGeometry
  MODE: DeterministicConvergence
  RANDOM: FORBIDDEN

GLYPH GeneratedCore
  TYPE: Module
  CONTAINER: Regular octagon (base 88)
  INTERNAL_GEOMETRY:
    - Golden spiral ({5} turns) = growth / learning
    - Inscribed triangle (1) = stability
    - Central dot (3) + crystalline facets (8) = parallel processing
    - Branching tree for decision logic
  INTRINSIC_VALUE: {intrinsic}
  INPUT_0: {desc_id} (gematria-reduced seed)
  45°: Recursion / self-nesting
  90°: Multiplication / composition
  180°: Branching tree (deterministic convergence)
  EVALUATION: Innermost-first (Rule 20)
  OUTPUT: Fully formed glyph program

// Rendering Description (Rule 29 - Automatic)
RENDERING
  Container: Large regular octagon, thin metallic gold border
  Central: Luminous gold dot (seed) with faint halo
  Spiral: Golden ratio spiral starting at center, expanding in 5 precise turns, lines thickening outward
  Triangle: Clean inscribed equilateral triangle, vertices touching midpoints of every other octagon side
  Facets: 8 crystalline facets symmetrically placed around the spiral
  Shading: Smooth dark-to-light gradient inside the octagon (darker near center, lighter toward edges)
  Output Rays: 8 equal-length golden rays extending outward from the central dot through the midpoints of each octagon side
  Central Output Circle: Slightly larger than the seed dot, diameter proportional to the resolved numeric result
  Aesthetic: Sacred geometry style — clean, harmonious, balanced, and alive. No text, no random elements. Every line, dot, and intersection contributes exactly to the intrinsic value.
  Intrinsic Value Breakdown: Base octagon (88) + spiral (40) + triangle (33) + dots (3) + facets (8) + intersections (6) = {intrinsic}

// End of Auto-Generated CodeScript
// Ready for Roman Wheel execution
"""
        return codescript.strip()

# ===================================================================
# Example usage (run this file directly)
# ===================================================================

if __name__ == "__main__":
    generator = OctaLangGlyphGenerator()
    user_input = input("Enter description for glyph generation: ").strip()
    if not user_input:
        user_input = "Seraphina AGI core with Mercy growth"
    
    result = generator.generate(user_input)
    print("\n" + "="*80)
    print("✅ OCTALANG GLYPH CODE GENERATED")
    print("="*80)
    print(result)
    print("\n✅ Rendering description included automatically (Rule 29)")
    print("✅ Fully deterministic • Compliant with all 29 rules")